var hierarchy =
[
    [ "Deki::AllocContext", "struct_deki_1_1_alloc_context.html", null ],
    [ "DekiEditor::AssetCacheContext", "struct_deki_editor_1_1_asset_cache_context.html", null ],
    [ "DekiEditor::AssetData", "struct_deki_editor_1_1_asset_data.html", null ],
    [ "DekiEditor::AssetDatabase", "class_deki_editor_1_1_asset_database.html", null ],
    [ "DekiEditor::AssetFileWatcher", "class_deki_editor_1_1_asset_file_watcher.html", null ],
    [ "Deki::LoadedPack::AssetInfo", "struct_deki_1_1_loaded_pack_1_1_asset_info.html", null ],
    [ "DekiEditor::AssetInfo", "struct_deki_editor_1_1_asset_info.html", null ],
    [ "Deki::AssetLookupTable", "class_deki_1_1_asset_lookup_table.html", null ],
    [ "Deki::AssetManager", "class_deki_1_1_asset_manager.html", null ],
    [ "Deki::AssetPackReader", "class_deki_1_1_asset_pack_reader.html", null ],
    [ "DekiEditor::AssetPicker", "class_deki_editor_1_1_asset_picker.html", null ],
    [ "DekiEditor::AssetPickerEntry", "struct_deki_editor_1_1_asset_picker_entry.html", null ],
    [ "DekiEditor::AssetPipeline", "class_deki_editor_1_1_asset_pipeline.html", null ],
    [ "Deki::AssetRefBase", "struct_deki_1_1_asset_ref_base.html", [
      [ "Deki::AssetRef< T >", "struct_deki_1_1_asset_ref.html", null ]
    ] ],
    [ "DekiEditor::AssetTypeEditorRegistry", "class_deki_editor_1_1_asset_type_editor_registry.html", null ],
    [ "DekiEditor::AssetTypeHandler", "struct_deki_editor_1_1_asset_type_handler.html", null ],
    [ "DekiEditor::AssetTypeRegistry", "class_deki_editor_1_1_asset_type_registry.html", null ],
    [ "DekiEditor::AtlasFrame", "struct_deki_editor_1_1_atlas_frame.html", null ],
    [ "Deki::AutoSetupRegistrar&lt; T, Phase &gt;", "struct_deki_1_1_auto_setup_registrar.html", null ],
    [ "Deki::Buffer&lt; T &gt;", "class_deki_1_1_buffer.html", null ],
    [ "DekiEditor::BuilderDefinition", "struct_deki_editor_1_1_builder_definition.html", null ],
    [ "DekiEditor::BuilderRegistry", "class_deki_editor_1_1_builder_registry.html", null ],
    [ "DekiEditor::BuildOptions", "struct_deki_editor_1_1_build_options.html", null ],
    [ "DekiEditor::BuildProgress", "struct_deki_editor_1_1_build_progress.html", null ],
    [ "DekiEditor::BuildStripSettings", "struct_deki_editor_1_1_build_strip_settings.html", null ],
    [ "DekiEditor::ChromaKeySettings", "struct_deki_editor_1_1_chroma_key_settings.html", null ],
    [ "DekiEditor::CliToolContext", "struct_deki_editor_1_1_cli_tool_context.html", null ],
    [ "Deki::Color", "class_deki_1_1_color.html", null ],
    [ "DekiEditor::Command", "class_deki_editor_1_1_command.html", [
      [ "DekiEditor::CompoundCommand", "class_deki_editor_1_1_compound_command.html", null ]
    ] ],
    [ "DekiEditor::CommandHistory", "class_deki_editor_1_1_command_history.html", null ],
    [ "Deki::Component", "class_deki_1_1_component.html", [
      [ "Deki::CoreProjectSettings", "class_deki_1_1_core_project_settings.html", null ],
      [ "Deki::DisplayProjectSettings", "class_deki_1_1_display_project_settings.html", null ],
      [ "Deki::PlatformSetupComponent", "class_deki_1_1_platform_setup_component.html", null ],
      [ "Deki::SetupComponent", "class_deki_1_1_setup_component.html", null ],
      [ "Deki::UnitProjectSettings", "class_deki_1_1_unit_project_settings.html", null ]
    ] ],
    [ "DekiEditor::ComponentDef", "struct_deki_editor_1_1_component_def.html", null ],
    [ "Deki::ComponentFactory", "class_deki_1_1_component_factory.html", null ],
    [ "Deki::ComponentMeta", "struct_deki_1_1_component_meta.html", null ],
    [ "Deki::ComponentRegistry", "class_deki_1_1_component_registry.html", null ],
    [ "Deki::ComponentTypeInfo", "struct_deki_1_1_component_type_info.html", null ],
    [ "DekiEditor::ComponentUsage", "struct_deki_editor_1_1_component_usage.html", null ],
    [ "CoreDependency", "struct_core_dependency.html", null ],
    [ "DekiEditor::CreateMenuEntry", "struct_deki_editor_1_1_create_menu_entry.html", null ],
    [ "DekiEditor::CreateMenuRegistry", "class_deki_editor_1_1_create_menu_registry.html", null ],
    [ "DekiEditor::CustomEditorRegistry", "class_deki_editor_1_1_custom_editor_registry.html", null ],
    [ "DekiEditor::DeadMemory", "class_deki_editor_1_1_dead_memory.html", null ],
    [ "DekiEditor::DecodedImage", "struct_deki_editor_1_1_decoded_image.html", null ],
    [ "DekiBuilderAbi", "struct_deki_builder_abi.html", null ],
    [ "DekiReflectionAbi", "struct_deki_reflection_abi.html", null ],
    [ "DependencyInfo", "struct_dependency_info.html", null ],
    [ "DekiEditor::DeployTarget", "struct_deki_editor_1_1_deploy_target.html", null ],
    [ "Deki::ProjectSettings::DisplaySettings", "struct_deki_1_1_project_settings_1_1_display_settings.html", null ],
    [ "DekiEditor::DownloadProgress", "struct_deki_editor_1_1_download_progress.html", null ],
    [ "Deki::DPackEntry", "struct_deki_1_1_d_pack_entry.html", null ],
    [ "Deki::DPackHeader", "struct_deki_1_1_d_pack_header.html", null ],
    [ "DekiEditor::EditorUI::EditCallbacksBytes", "struct_deki_editor_1_1_editor_u_i_1_1_edit_callbacks_bytes.html", null ],
    [ "DekiEditor::EditorApplication", "class_deki_editor_1_1_editor_application.html", null ],
    [ "DekiEditor::EditorAssets", "class_deki_editor_1_1_editor_assets.html", null ],
    [ "DekiEditor::EditorExtension", "class_deki_editor_1_1_editor_extension.html", [
      [ "DekiEditor::AssetTypeEditor", "class_deki_editor_1_1_asset_type_editor.html", null ],
      [ "DekiEditor::CliTool", "class_deki_editor_1_1_cli_tool.html", null ],
      [ "DekiEditor::CustomEditor", "class_deki_editor_1_1_custom_editor.html", null ],
      [ "DekiEditor::FileInspector", "class_deki_editor_1_1_file_inspector.html", null ]
    ] ],
    [ "DekiEditorInternal::EditorFactoryInfo", "struct_deki_editor_internal_1_1_editor_factory_info.html", null ],
    [ "DekiEditor::EditorHttpUtils", "class_deki_editor_1_1_editor_http_utils.html", null ],
    [ "DekiEditor::EditorPaths", "class_deki_editor_1_1_editor_paths.html", null ],
    [ "DekiEditorInternal::EditorRegistrar&lt; T &gt;", "struct_deki_editor_internal_1_1_editor_registrar.html", null ],
    [ "DekiEditorInternal::EditorRegistry", "class_deki_editor_internal_1_1_editor_registry.html", null ],
    [ "DekiEditor::EditorSettings", "class_deki_editor_1_1_editor_settings.html", null ],
    [ "DekiEditor::EditorUI", "class_deki_editor_1_1_editor_u_i.html", null ],
    [ "DekiEditor::EditorWindow", "class_deki_editor_1_1_editor_window.html", null ],
    [ "DekiEditor::EditorWindowMeta", "struct_deki_editor_1_1_editor_window_meta.html", null ],
    [ "Deki::Engine", "class_deki_1_1_engine.html", null ],
    [ "Deki::EngineHost", "struct_deki_1_1_engine_host.html", null ],
    [ "Deki::EngineSettings", "struct_deki_1_1_engine_settings.html", null ],
    [ "DekiEditor::EditorUI::EnumCallbacks", "struct_deki_editor_1_1_editor_u_i_1_1_enum_callbacks.html", null ],
    [ "DekiEditor::AssetFileWatcher::Event", "struct_deki_editor_1_1_asset_file_watcher_1_1_event.html", null ],
    [ "DekiEditor::FallbackDef", "struct_deki_editor_1_1_fallback_def.html", null ],
    [ "DekiEditor::FeatureDecision", "struct_deki_editor_1_1_feature_decision.html", null ],
    [ "DekiEditor::CMakeGen::FeatureEntry", "struct_deki_editor_1_1_c_make_gen_1_1_feature_entry.html", null ],
    [ "Deki::FieldRef", "struct_deki_1_1_field_ref.html", null ],
    [ "Deki::ProjectSettings::FileHeader", "struct_deki_1_1_project_settings_1_1_file_header.html", null ],
    [ "DekiEditor::FileInspectorRegistry", "class_deki_editor_1_1_file_inspector_registry.html", null ],
    [ "Deki::FileSystem", "class_deki_1_1_file_system.html", null ],
    [ "DekiEditor::EditorUI::FloatCallbacks", "struct_deki_editor_1_1_editor_u_i_1_1_float_callbacks.html", null ],
    [ "Deki::FPSCounter", "class_deki_1_1_f_p_s_counter.html", null ],
    [ "DekiEditor::CMakeGen::FrameworkDependency", "struct_deki_editor_1_1_c_make_gen_1_1_framework_dependency.html", null ],
    [ "DekiEditor::GuidCache", "class_deki_editor_1_1_guid_cache.html", null ],
    [ "Deki::Texture2D::Header", "struct_deki_1_1_texture2_d_1_1_header.html", null ],
    [ "DekiEditor::IAssetImporter", "class_deki_editor_1_1_i_asset_importer.html", [
      [ "DekiEditor::TextureImporter", "class_deki_editor_1_1_texture_importer.html", null ]
    ] ],
    [ "DekiEditor::IBuildActivitySink", "class_deki_editor_1_1_i_build_activity_sink.html", null ],
    [ "Deki::ICamera", "class_deki_1_1_i_camera.html", null ],
    [ "Deki::IClipProvider", "class_deki_1_1_i_clip_provider.html", null ],
    [ "Deki::IDisplay", "class_deki_1_1_i_display.html", null ],
    [ "Deki::IFileSystem", "class_deki_1_1_i_file_system.html", null ],
    [ "Deki::IInputSystem", "class_deki_1_1_i_input_system.html", null ],
    [ "Deki::IMemoryProvider", "class_deki_1_1_i_memory_provider.html", [
      [ "Deki::HostMemoryProvider", "class_deki_1_1_host_memory_provider.html", null ]
    ] ],
    [ "DekiEditor::ImportResult", "struct_deki_editor_1_1_import_result.html", null ],
    [ "DekiEditor::EditorUI::IntCallbacks", "struct_deki_editor_1_1_editor_u_i_1_1_int_callbacks.html", null ],
    [ "Deki::IPackage", "class_deki_1_1_i_package.html", null ],
    [ "IPackageInstaller", "class_i_package_installer.html", null ],
    [ "IPackageSource", "class_i_package_source.html", null ],
    [ "DekiEditor::IPlatformEditorUI", "class_deki_editor_1_1_i_platform_editor_u_i.html", null ],
    [ "Deki::IPower", "class_deki_1_1_i_power.html", null ],
    [ "Deki::IRenderSystem", "class_deki_1_1_i_render_system.html", null ],
    [ "Deki::ISortableProvider", "class_deki_1_1_i_sortable_provider.html", null ],
    [ "DekiEditor::ITargetBuilder", "class_deki_editor_1_1_i_target_builder.html", [
      [ "DekiEditor::FirmwareBuilderBase", "class_deki_editor_1_1_firmware_builder_base.html", null ]
    ] ],
    [ "Deki::ITimeProvider", "class_deki_1_1_i_time_provider.html", null ],
    [ "Deki::LoadedPack", "struct_deki_1_1_loaded_pack.html", null ],
    [ "Deki::LogSystem", "class_deki_1_1_log_system.html", null ],
    [ "Deki::Mat4", "struct_deki_1_1_mat4.html", null ],
    [ "Deki::Memory", "class_deki_1_1_memory.html", null ],
    [ "Deki::MemoryStats", "struct_deki_1_1_memory_stats.html", null ],
    [ "DekiEditor::NodeCanvas", "class_deki_editor_1_1_node_canvas.html", null ],
    [ "DekiEditor::NodeCanvasEvents", "struct_deki_editor_1_1_node_canvas_events.html", null ],
    [ "DekiEditor::NodeCanvasLink", "struct_deki_editor_1_1_node_canvas_link.html", null ],
    [ "DekiEditor::NodeCanvasNode", "struct_deki_editor_1_1_node_canvas_node.html", null ],
    [ "DekiEditor::NodeCanvasPalette", "struct_deki_editor_1_1_node_canvas_palette.html", null ],
    [ "Deki::NodeRef", "struct_deki_1_1_node_ref.html", null ],
    [ "Deki::Object", "class_deki_1_1_object.html", null ],
    [ "Deki::ObjectRefBase", "struct_deki_1_1_object_ref_base.html", [
      [ "Deki::ObjectRef< T >", "struct_deki_1_1_object_ref.html", null ]
    ] ],
    [ "Deki::PackageConfig", "struct_deki_1_1_package_config.html", null ],
    [ "DekiEditor::PackageDecision", "struct_deki_editor_1_1_package_decision.html", null ],
    [ "DekiEditor::EditorSettings::PackageDepInfo", "struct_deki_editor_1_1_editor_settings_1_1_package_dep_info.html", null ],
    [ "DekiEditor::CMakeGen::PackageEntry", "struct_deki_editor_1_1_c_make_gen_1_1_package_entry.html", null ],
    [ "PackageEntry", "struct_package_entry.html", null ],
    [ "Deki::PackIndexEntry", "struct_deki_1_1_pack_index_entry.html", null ],
    [ "DekiEditor::PickerItem", "struct_deki_editor_1_1_picker_item.html", null ],
    [ "DekiEditor::PlatformConfig", "struct_deki_editor_1_1_platform_config.html", null ],
    [ "DekiEditor::PlatformRegistry", "class_deki_editor_1_1_platform_registry.html", null ],
    [ "DekiEditor::PlatformTemplate", "struct_deki_editor_1_1_platform_template.html", null ],
    [ "DekiEditor::PostInstallDef", "struct_deki_editor_1_1_post_install_def.html", null ],
    [ "Deki::Power", "class_deki_1_1_power.html", null ],
    [ "Deki::PropertyBinding", "struct_deki_1_1_property_binding.html", null ],
    [ "Deki::PropertyInfo", "struct_deki_1_1_property_info.html", null ],
    [ "Deki::PropertyRef", "struct_deki_1_1_property_ref.html", null ],
    [ "Deki::Rect", "struct_deki_1_1_rect.html", null ],
    [ "Deki::Memory::Region", "struct_deki_1_1_memory_1_1_region.html", null ],
    [ "Deki::ProjectSettings::RuntimeSettings", "struct_deki_1_1_project_settings_1_1_runtime_settings.html", null ],
    [ "Deki::Scene", "class_deki_1_1_scene.html", null ],
    [ "Deki::SceneFormat::SceneMsgPackParser", "class_deki_1_1_scene_format_1_1_scene_msg_pack_parser.html", null ],
    [ "Deki::SceneFormat::SceneMsgPackWriter", "class_deki_1_1_scene_format_1_1_scene_msg_pack_writer.html", null ],
    [ "Deki::SceneSystem", "class_deki_1_1_scene_system.html", null ],
    [ "DekiEditor::SceneView", "class_deki_editor_1_1_scene_view.html", null ],
    [ "DekiEditor::SceneViewContext", "struct_deki_editor_1_1_scene_view_context.html", null ],
    [ "Deki::SettingsRegistry", "class_deki_1_1_settings_registry.html", null ],
    [ "Deki::SettingsTypeInfo", "struct_deki_1_1_settings_type_info.html", null ],
    [ "Deki::IPower::SleepInfo", "struct_deki_1_1_i_power_1_1_sleep_info.html", null ],
    [ "DekiEditor::SpriteFrameData", "struct_deki_editor_1_1_sprite_frame_data.html", null ],
    [ "DekiEditor::SpriteSettings", "struct_deki_editor_1_1_sprite_settings.html", null ],
    [ "DekiEditor::StripPlan", "struct_deki_editor_1_1_strip_plan.html", null ],
    [ "DekiEditor::SubAssetInfo", "struct_deki_editor_1_1_sub_asset_info.html", null ],
    [ "DekiEditor::SubComponentDef", "struct_deki_editor_1_1_sub_component_def.html", null ],
    [ "DekiEditor::TargetContentConflict", "struct_deki_editor_1_1_target_content_conflict.html", null ],
    [ "DekiEditor::TexData", "struct_deki_editor_1_1_tex_data.html", null ],
    [ "DekiEditor::TexHeader", "struct_deki_editor_1_1_tex_header.html", null ],
    [ "DekiEditor::EditorUI::TextCallbacks", "struct_deki_editor_1_1_editor_u_i_1_1_text_callbacks.html", null ],
    [ "Deki::Texture2D", "class_deki_1_1_texture2_d.html", null ],
    [ "Deki::Time", "class_deki_1_1_time.html", null ],
    [ "DekiEditor::ToolchainComponent", "struct_deki_editor_1_1_toolchain_component.html", null ],
    [ "DekiEditor::ToolchainComponentManager", "class_deki_editor_1_1_toolchain_component_manager.html", null ],
    [ "DekiEditor::ToolchainVersionInfo", "struct_deki_editor_1_1_toolchain_version_info.html", null ],
    [ "Deki::detail::TypeNameProbe", "struct_deki_1_1detail_1_1_type_name_probe.html", null ],
    [ "Deki::detail::TypeNameStorage&lt; T, Seq &gt;", "struct_deki_1_1detail_1_1_type_name_storage.html", null ],
    [ "Deki::detail::TypeShortNameStorage&lt; T, Seq &gt;", "struct_deki_1_1detail_1_1_type_short_name_storage.html", null ],
    [ "DekiEditor::EditorUI::VecCallbacks", "struct_deki_editor_1_1_editor_u_i_1_1_vec_callbacks.html", null ],
    [ "Deki::Vector&lt; T &gt;", "class_deki_1_1_vector.html", null ],
    [ "Deki::Vector2", "struct_deki_1_1_vector2.html", null ],
    [ "Deki::Vector3", "struct_deki_1_1_vector3.html", null ],
    [ "DekiEditor::VersionCheckDef", "struct_deki_editor_1_1_version_check_def.html", null ],
    [ "DekiEditor::EditorUI::WidgetBackend", "struct_deki_editor_1_1_editor_u_i_1_1_widget_backend.html", null ]
];