var hierarchy =
[
    [ "DekiEditor::AssetCacheContext", "struct_deki_editor_1_1_asset_cache_context.html", null ],
    [ "DekiEditor::AssetData", "struct_deki_editor_1_1_asset_data.html", null ],
    [ "DekiEditor::AssetDatabase", "class_deki_editor_1_1_asset_database.html", null ],
    [ "DekiEditor::AssetFileWatcher", "class_deki_editor_1_1_asset_file_watcher.html", null ],
    [ "Deki::LoadedPack::AssetInfo", "struct_deki_1_1_loaded_pack_1_1_asset_info.html", null ],
    [ "DekiEditor::AssetInfo", "struct_deki_editor_1_1_asset_info.html", null ],
    [ "Deki::AssetLookupTable", "class_deki_1_1_asset_lookup_table.html", null ],
    [ "Deki::AssetManager", "class_deki_1_1_asset_manager.html", null ],
    [ "Deki::AssetPackReader", "class_deki_1_1_asset_pack_reader.html", null ],
    [ "DekiEditor::AssetPicker", "class_deki_editor_1_1_asset_picker.html", null ],
    [ "DekiEditor::AssetPickerEntry", "struct_deki_editor_1_1_asset_picker_entry.html", null ],
    [ "DekiEditor::AssetPipeline", "class_deki_editor_1_1_asset_pipeline.html", null ],
    [ "Deki::AssetRefBase", "struct_deki_1_1_asset_ref_base.html", [
      [ "Deki::AssetRef< T >", "struct_deki_1_1_asset_ref.html", null ]
    ] ],
    [ "DekiEditor::AssetTypeEditorRegistry", "class_deki_editor_1_1_asset_type_editor_registry.html", null ],
    [ "DekiEditor::AssetTypeHandler", "struct_deki_editor_1_1_asset_type_handler.html", null ],
    [ "DekiEditor::AssetTypeRegistry", "class_deki_editor_1_1_asset_type_registry.html", null ],
    [ "DekiEditor::AtlasFrame", "struct_deki_editor_1_1_atlas_frame.html", null ],
    [ "DekiEditor::ChromaKeySettings", "struct_deki_editor_1_1_chroma_key_settings.html", null ],
    [ "Deki::Color", "class_deki_1_1_color.html", null ],
    [ "DekiEditor::Command", "class_deki_editor_1_1_command.html", [
      [ "DekiEditor::CompoundCommand", "class_deki_editor_1_1_compound_command.html", null ]
    ] ],
    [ "DekiEditor::CommandHistory", "class_deki_editor_1_1_command_history.html", null ],
    [ "SceneFormat::ComponentFactory", "class_scene_format_1_1_component_factory.html", null ],
    [ "ComponentRegistry", "class_component_registry.html", null ],
    [ "DekiEditor::CreateMenuEntry", "struct_deki_editor_1_1_create_menu_entry.html", null ],
    [ "DekiEditor::CreateMenuRegistry", "class_deki_editor_1_1_create_menu_registry.html", null ],
    [ "DekiEditor::CustomEditorRegistry", "class_deki_editor_1_1_custom_editor_registry.html", null ],
    [ "DekiEditor::DeadMemory", "class_deki_editor_1_1_dead_memory.html", null ],
    [ "DekiEditor::DecodedImage", "struct_deki_editor_1_1_decoded_image.html", null ],
    [ "DekiComponent", "class_deki_component.html", [
      [ "CoreProjectSettings", "class_core_project_settings.html", null ],
      [ "DekiBehaviour", "class_deki_behaviour.html", [
        [ "PlatformSetupComponent", "class_platform_setup_component.html", null ],
        [ "SetupComponent", "class_setup_component.html", null ]
      ] ],
      [ "DisplayProjectSettings", "class_display_project_settings.html", null ],
      [ "MissingComponent", "class_missing_component.html", null ],
      [ "UnitProjectSettings", "class_unit_project_settings.html", null ]
    ] ],
    [ "DekiComponentMeta", "struct_deki_component_meta.html", null ],
    [ "DekiEngine", "class_deki_engine.html", null ],
    [ "DekiEngineHost", "struct_deki_engine_host.html", null ],
    [ "DekiEngineSettings", "struct_deki_engine_settings.html", null ],
    [ "DekiFieldRef", "struct_deki_field_ref.html", null ],
    [ "DekiFileSystem", "class_deki_file_system.html", null ],
    [ "DekiFPSCounter", "class_deki_f_p_s_counter.html", null ],
    [ "DekiLogSystem", "class_deki_log_system.html", null ],
    [ "DekiMemory", "class_deki_memory.html", null ],
    [ "DekiMemoryStats", "struct_deki_memory_stats.html", null ],
    [ "DekiObject", "class_deki_object.html", null ],
    [ "DekiPower", "class_deki_power.html", null ],
    [ "DekiPropertyInfo", "struct_deki_property_info.html", null ],
    [ "DekiProviderRegistry&lt; Interface &gt;", "class_deki_provider_registry.html", null ],
    [ "DekiProviderRegistryBase", "class_deki_provider_registry_base.html", null ],
    [ "DekiRect", "struct_deki_rect.html", null ],
    [ "DekiReflectionAbi", "struct_deki_reflection_abi.html", null ],
    [ "DekiSettingsRegistry", "class_deki_settings_registry.html", null ],
    [ "DekiSettingsTypeInfo", "struct_deki_settings_type_info.html", null ],
    [ "DekiTime", "class_deki_time.html", null ],
    [ "DekiVector2", "struct_deki_vector2.html", null ],
    [ "DekiVector3", "struct_deki_vector3.html", null ],
    [ "DekiWorldTransform", "struct_deki_world_transform.html", null ],
    [ "ProjectSettings::DisplaySettings", "struct_project_settings_1_1_display_settings.html", null ],
    [ "Deki::DPackEntry", "struct_deki_1_1_d_pack_entry.html", null ],
    [ "Deki::DPackHeader", "struct_deki_1_1_d_pack_header.html", null ],
    [ "DekiEditor::EditorUI::EditCallbacksBytes", "struct_deki_editor_1_1_editor_u_i_1_1_edit_callbacks_bytes.html", null ],
    [ "DekiEditor::EditorApplication", "class_deki_editor_1_1_editor_application.html", null ],
    [ "DekiEditor::EditorAssets", "class_deki_editor_1_1_editor_assets.html", null ],
    [ "EditorAutoSetupRegistrar&lt; T &gt;", "struct_editor_auto_setup_registrar.html", null ],
    [ "DekiEditor::EditorExtension", "class_deki_editor_1_1_editor_extension.html", [
      [ "DekiEditor::AssetTypeEditor", "class_deki_editor_1_1_asset_type_editor.html", null ],
      [ "DekiEditor::CustomEditor", "class_deki_editor_1_1_custom_editor.html", null ],
      [ "DekiEditor::FileInspector", "class_deki_editor_1_1_file_inspector.html", null ]
    ] ],
    [ "DekiEditorInternal::EditorFactoryInfo", "struct_deki_editor_internal_1_1_editor_factory_info.html", null ],
    [ "DekiEditor::EditorHttpUtils", "class_deki_editor_1_1_editor_http_utils.html", null ],
    [ "DekiEditor::EditorPaths", "class_deki_editor_1_1_editor_paths.html", null ],
    [ "DekiEditorInternal::EditorRegistrar&lt; T &gt;", "struct_deki_editor_internal_1_1_editor_registrar.html", null ],
    [ "DekiEditorInternal::EditorRegistry", "class_deki_editor_internal_1_1_editor_registry.html", null ],
    [ "DekiEditor::EditorUI", "class_deki_editor_1_1_editor_u_i.html", null ],
    [ "DekiEditor::EditorWindow", "class_deki_editor_1_1_editor_window.html", null ],
    [ "DekiEditor::EditorWindowMeta", "struct_deki_editor_1_1_editor_window_meta.html", null ],
    [ "DekiEditor::EditorUI::EnumCallbacks", "struct_deki_editor_1_1_editor_u_i_1_1_enum_callbacks.html", null ],
    [ "DekiEditor::AssetFileWatcher::Event", "struct_deki_editor_1_1_asset_file_watcher_1_1_event.html", null ],
    [ "ProjectSettings::FileHeader", "struct_project_settings_1_1_file_header.html", null ],
    [ "DekiEditor::FileInspectorRegistry", "class_deki_editor_1_1_file_inspector_registry.html", null ],
    [ "DekiEditor::EditorUI::FloatCallbacks", "struct_deki_editor_1_1_editor_u_i_1_1_float_callbacks.html", null ],
    [ "DekiEditor::GuidCache", "class_deki_editor_1_1_guid_cache.html", null ],
    [ "DekiEditor::IAssetImporter", "class_deki_editor_1_1_i_asset_importer.html", [
      [ "DekiEditor::TextureImporter", "class_deki_editor_1_1_texture_importer.html", null ]
    ] ],
    [ "ICamera", "class_i_camera.html", null ],
    [ "IClipProvider", "class_i_clip_provider.html", null ],
    [ "IDekiDisplay", "class_i_deki_display.html", [
      [ "EditorDisplay", "class_editor_display.html", null ]
    ] ],
    [ "IDekiFileSystem", "class_i_deki_file_system.html", [
      [ "DesktopFileSystem", "class_desktop_file_system.html", null ]
    ] ],
    [ "IDekiInputSystem", "class_i_deki_input_system.html", null ],
    [ "IDekiPackage", "class_i_deki_package.html", null ],
    [ "IDekiPower", "class_i_deki_power.html", null ],
    [ "IDekiRenderSystem", "class_i_deki_render_system.html", null ],
    [ "IMemoryProvider", "class_i_memory_provider.html", [
      [ "DesktopMemoryProvider", "class_desktop_memory_provider.html", null ]
    ] ],
    [ "DekiEditor::ImportResult", "struct_deki_editor_1_1_import_result.html", null ],
    [ "DekiEditor::EditorUI::IntCallbacks", "struct_deki_editor_1_1_editor_u_i_1_1_int_callbacks.html", null ],
    [ "ISortableProvider", "class_i_sortable_provider.html", null ],
    [ "ITimeProvider", "class_i_time_provider.html", null ],
    [ "LifecycleManager", "class_lifecycle_manager.html", null ],
    [ "Deki::LoadedPack", "struct_deki_1_1_loaded_pack.html", null ],
    [ "Mat4", "struct_mat4.html", null ],
    [ "DekiEditor::NodeCanvas", "class_deki_editor_1_1_node_canvas.html", null ],
    [ "DekiEditor::NodeCanvasEvents", "struct_deki_editor_1_1_node_canvas_events.html", null ],
    [ "DekiEditor::NodeCanvasLink", "struct_deki_editor_1_1_node_canvas_link.html", null ],
    [ "DekiEditor::NodeCanvasNode", "struct_deki_editor_1_1_node_canvas_node.html", null ],
    [ "DekiEditor::NodeCanvasPalette", "struct_deki_editor_1_1_node_canvas_palette.html", null ],
    [ "NodeRef", "struct_node_ref.html", null ],
    [ "ObjectRefBase", "struct_object_ref_base.html", [
      [ "ObjectRef< T >", "struct_object_ref.html", null ]
    ] ],
    [ "PackageConfig", "struct_package_config.html", null ],
    [ "Deki::PackIndexEntry", "struct_deki_1_1_pack_index_entry.html", null ],
    [ "DekiEditor::PickerItem", "struct_deki_editor_1_1_picker_item.html", null ],
    [ "ProjectSettings::PipelineConfig", "struct_project_settings_1_1_pipeline_config.html", null ],
    [ "PropertyBinding", "struct_property_binding.html", null ],
    [ "PropertyRef", "struct_property_ref.html", null ],
    [ "ProjectSettings::RuntimeSettings", "struct_project_settings_1_1_runtime_settings.html", null ],
    [ "Scene", "class_scene.html", null ],
    [ "SceneFormat::SceneMsgPackParser", "class_scene_format_1_1_scene_msg_pack_parser.html", null ],
    [ "SceneFormat::SceneMsgPackWriter", "class_scene_format_1_1_scene_msg_pack_writer.html", null ],
    [ "SceneSystem", "class_scene_system.html", null ],
    [ "DekiEditor::SceneView", "class_deki_editor_1_1_scene_view.html", null ],
    [ "DekiEditor::SceneViewContext", "struct_deki_editor_1_1_scene_view_context.html", null ],
    [ "IDekiPower::SleepInfo", "struct_i_deki_power_1_1_sleep_info.html", null ],
    [ "DekiEditor::SpriteFrameData", "struct_deki_editor_1_1_sprite_frame_data.html", null ],
    [ "DekiEditor::SpriteSettings", "struct_deki_editor_1_1_sprite_settings.html", null ],
    [ "DekiEditor::SubAssetInfo", "struct_deki_editor_1_1_sub_asset_info.html", null ],
    [ "DekiEditor::TexData", "struct_deki_editor_1_1_tex_data.html", null ],
    [ "DekiEditor::TexHeader", "struct_deki_editor_1_1_tex_header.html", null ],
    [ "DekiEditor::EditorUI::TextCallbacks", "struct_deki_editor_1_1_editor_u_i_1_1_text_callbacks.html", null ],
    [ "DekiEditor::EditorUI::VecCallbacks", "struct_deki_editor_1_1_editor_u_i_1_1_vec_callbacks.html", null ],
    [ "DekiEditor::EditorUI::WidgetBackend", "struct_deki_editor_1_1_editor_u_i_1_1_widget_backend.html", null ]
];